### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [surfacepatterns/midisnoop#2]
```
When trying to build midisnoop-0.1.2 I get the following error:

g++ -c -m64 -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector 
--param=ssp-buffer-size=4 -m64 -mtune=generic -Wall -W -D_REENTRANT 
-DMIDISNOOP_PLATFORM_UNIX -DMIDISNOOP_MAJOR_VERSION=0 
-DMIDISNOOP_MINOR_VERSION=1 -DMIDISNOOP_REVISION=0 -DQT_NO_DEBUG -DQT_XML_LIB 
-DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib64/qt4/mkspecs/linux-g++-64 -I. 
-I/usr/include/QtUiTools -I/usr/include/QtCore -I/usr/include/QtGui 
-I/usr/include/QtXml -I/usr/include -I../make -o ../make/engine.o engine.cpp
engine.cpp: In member function ‘void Engine::handleMidiInput(double, 
std::vector<unsigned char, std::allocator<unsigned char> >*)’:
engine.cpp:168: error: ‘class QDateTime’ has no member named 
‘toMSecsSinceEpoch’
engine.cpp: In member function ‘quint64 Engine::sendMessage(const 
QByteArray&)’:
engine.cpp:205: error: ‘class QDateTime’ has no member named 
‘toMSecsSinceEpoch’
make[1]: *** [../make/engine.o] Error 1
make[1]: Leaving directory `/home/packager/rpm/tmp/midisnoop-0.1.2/src'
make: *** [sub-src-make_default] Error 2


This is on CentOS 6.3 with rtmidi 2.0.1 installed from source with ALSA and 
Jack support built in.

```

Original issue reported on code.google.com by `adr-goog...@uridium.org` on 27 Feb 2013 at 12:09

**Comment by GoogleCodeExporter** [comment]
```
What version of Qt are you compiling against?
```

Original comment by `surfacep...@gmail.com` on 27 Feb 2013 at 1:55

**Comment by GoogleCodeExporter** [comment]
```
QT 4.6.2, the version that ships with CentOS 6.3.

```

Original comment by `adr-goog...@uridium.org` on 27 Feb 2013 at 9:42

**Comment by GoogleCodeExporter** [comment]
```
I found the following related discussion:
http://forums.openpilot.org/topic/3204-is-qt-47-mandatory-now/

Would it be possible to use 'toTime_t' instead of 'toMSecsSinceEpoch' as 
suggested in that thread so that midisnoop builds with QT < 4.7 too?

QT is a fundamental system package with loads of dependencies so unfortunately 
I can't upgrade it to a newer version.
```

Original comment by `adr-goog...@uridium.org` on 27 Feb 2013 at 10:40

**Comment by GoogleCodeExporter** [comment]
```
The resolution of toTime_t () is seconds, which isn't useful for these 
timestamps.  I'll do a bit of research later on how to solve this problem.
```

Original comment by `surfacep...@gmail.com` on 27 Feb 2013 at 11:03

**Comment by GoogleCodeExporter** [comment]
```
I've added what I *believe* is a fix to trunk.  Check the source out from trunk 
and let me know if the fix works for you.
```

Original comment by `surfacep...@gmail.com` on 28 Feb 2013 at 6:05
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Many thanks! Midisnoop now builds without errors on Centos 6.3 and the program 
runs fine when I launch it, so I guess you can close this issue.
I haven't tested snooping actual MIDI traffic yet, but if I notice any 
time-stamp problems when doing that I will open a new issue.
```

Original comment by `adr-goog...@uridium.org` on 28 Feb 2013 at 10:56

**Comment by GoogleCodeExporter** [comment]
```
You're very welcome.  Let me know if you run into any more issues.
```

Original comment by `surfacep...@gmail.com` on 28 Feb 2013 at 5:55
- Changed state: **Fixed**
